micronaut.application.name=proper-anki
micronaut.server.port=8080
micronaut.server.cors.enabled=true
datasources.default.url=jdbc:sqlite:${APP_DATA_DIR:./data}/proper-anki.db
datasources.default.driver-class-name=org.sqlite.JDBC
datasources.default.db-type=SQLITE
datasources.default.maximum-pool-size=5
app.image-dir=${APP_DATA_DIR:./data}/images
