micronaut.application.name=proper-anki
micronaut.server.port=8080
micronaut.server.cors.enabled=true

datasources.default.url=${JDBC_URL:jdbc:postgresql://localhost:5432/db}
datasources.default.username=${POSTGRES_USER:proper_anki}
datasources.default.password=${POSTGRES_PASSWORD:proper_anki}
datasources.default.driver-class-name=org.postgresql.Driver
datasources.default.db-type=POSTGRES
datasources.default.maximum-pool-size=5
datasources.default.schema-generate=NONE

app.image-dir=${APP_DATA_DIR:./data}/images
